### ISSUE TITLE
Doesn't work with mod maps

### ISSUE THREAD

**Issue by Krucifixionador** [ark-mod/ArkBot#40] opened 2018-01-17 22:30 UTC
I have seen that I can not manage one of my maps, specifically the TheVolcano map. Apparently only allows to manage official maps. What I can think of that can give problems is the map image, so I think ... What if the map images came in a folder and I took them from there? So we can also customize it a bit, and use the map image we create more convenient. Hopefully it can be solved easily ^^.

**Comment by Magesw** [comment] 2018-01-17 22:45
I like that idea, not sure where the maps are currently coming from but if we could just have them in a folder we could add our own for custom maps.

**Comment by tsebring** [comment] 2018-01-18 09:15
It's not just the map image that is different per map. There are coordinate conversions from `X, Y, Z` to `Latitude, Longitude` and subsequently into image pixel coordinates.

It is currently configured in the dependency ArkSavegameToolkitNet for the maps that are supported https://github.com/tsebring/ArkSavegameToolkitNet/blob/master/ArkSavegameToolkitNet.Domain/ArkLocation.cs

Adding more supported maps require all these pieces to be figured out by someone.

In the future, it would be nice to have this configuration exposed to the user rather than hardcoded in the external dependency. Not sure how widely used it would be though since finding a proper map and the conversion functions are not super easy.

**Comment by SirShaw** [comment] 2020-01-01 01:23
duplicate of #51

**Closed by SirShaw** 2020-01-01 01:23 UTC
Labels: application, feature
